#include "ExperimentConfig.h"
#include <fstream>
#include <nlohmann/json.hpp>
using json=nlohmann::json;
static std::string gs(const json&j,const char*k,const std::string&d){return j.contains(k)?j.at(k).get<std::string>():d;}
static double gd(const json&j,const char*k,double d){return j.contains(k)?j.at(k).get<double>():d;}
static int gi(const json&j,const char*k,int d){return j.contains(k)?j.at(k).get<int>():d;}
static bool gb(const json&j,const char*k,bool d){return j.contains(k)?j.at(k).get<bool>():d;}
bool ExperimentConfig::loadFromFile(const std::string& p, ExperimentConfig& c, std::string& e){std::ifstream ifs(p); if(!ifs){e="cannot open config: "+p; return false;} json j; ifs>>j; c.experiment_name=gs(j,"experiment_name",c.experiment_name); c.benchmark=gs(j,"benchmark",c.benchmark); c.cost_mode=gs(j,"cost_mode",c.cost_mode); if(j.contains("input")){auto&i=j["input"]; c.input.common_lef=gs(i,"common_lef",""); c.input.hbt_lef=gs(i,"hbt_lef",""); c.input.upper_lef=gs(i,"upper_lef",""); c.input.bottom_lef=gs(i,"bottom_lef",""); c.input.def_file=gs(i,"def_file",""); if(i.contains("extra_lefs")) c.input.extra_lefs=i["extra_lefs"].get<std::vector<std::string>>();}
if(j.contains("output")){auto&o=j["output"]; c.output.output_dir=gs(o,"output_dir",c.output.output_dir); c.output.summary_report=gs(o,"summary_report",c.output.summary_report); c.output.net_info=gs(o,"net_info",c.output.net_info); c.output.plot_data_dir=gs(o,"plot_data_dir",c.output.plot_data_dir); c.output.plot_dir=gs(o,"plot_dir",c.output.plot_dir); c.output.enable_plot_generation=gb(o,"enable_plot_generation",c.output.enable_plot_generation); c.output.dump_invalid_3d_nets=gb(o,"dump_invalid_3d_nets",c.output.dump_invalid_3d_nets);} if(j.contains("pd_tree")){auto&pdt=j["pd_tree"]; c.pd_tree.max_nets=gi(pdt,"max_nets",c.pd_tree.max_nets); c.pd_tree.max_candidate_parents=gi(pdt,"max_candidate_parents",c.pd_tree.max_candidate_parents); c.pd_tree.max_candidate_hbts=gi(pdt,"max_candidate_hbts",c.pd_tree.max_candidate_hbts); c.pd_tree.beam_width_3d=gi(pdt,"beam_width_3d",c.pd_tree.beam_width_3d); c.pd_tree.beam_branch_candidates_3d=gi(pdt,"beam_branch_candidates_3d",c.pd_tree.beam_branch_candidates_3d); c.pd_tree.max_local_hbt_candidates=gi(pdt,"max_local_hbt_candidates",c.pd_tree.max_local_hbt_candidates); c.pd_tree.max_hbt_nearest_k=gi(pdt,"max_hbt_nearest_k",c.pd_tree.max_hbt_nearest_k); c.pd_tree.verbose=gb(pdt,"verbose",c.pd_tree.verbose);} if(j.contains("cost_weights")){auto&w=j["cost_weights"]; c.cost_weights.avg_delay=gd(w,"avg_delay",c.cost_weights.avg_delay); c.cost_weights.max_delay=gd(w,"max_delay",c.cost_weights.max_delay); c.cost_weights.wirelength=gd(w,"wirelength",c.cost_weights.wirelength); c.cost_weights.hbt_count=gd(w,"hbt_count",c.cost_weights.hbt_count); c.cost_weights.stretch=gd(w,"stretch",c.cost_weights.stretch); c.cost_weights.hbt_depth=gd(w,"hbt_depth",c.cost_weights.hbt_depth); c.cost_weights.hbt_stack=gd(w,"hbt_stack",c.cost_weights.hbt_stack); c.cost_weights.hbt_fanout=gd(w,"hbt_fanout",c.cost_weights.hbt_fanout); c.cost_weights.hbt_scarcity=gd(w,"hbt_scarcity",c.cost_weights.hbt_scarcity); c.cost_weights.hbt_position=gd(w,"hbt_position",c.cost_weights.hbt_position); c.cost_weights.hbt_subtree_wire=gd(w,"hbt_subtree_wire",c.cost_weights.hbt_subtree_wire); c.cost_weights.hbt_subtree_delay_proxy=gd(w,"hbt_subtree_delay_proxy",c.cost_weights.hbt_subtree_delay_proxy);} if(j.contains("rc")){auto&r=j["rc"]; c.rc.source_res=gd(r,"source_res",c.rc.source_res); c.rc.default_sink_cap=gd(r,"default_sink_cap",c.rc.default_sink_cap); c.rc.hbt_res=gd(r,"hbt_res",c.rc.hbt_res); c.rc.hbt_cap=gd(r,"hbt_cap",c.rc.hbt_cap); c.rc.hbt_rc_scale=gd(r,"hbt_rc_scale",c.rc.hbt_rc_scale); c.rc.wire_r_scale=gd(r,"wire_r_scale",c.rc.wire_r_scale); c.rc.wire_c_scale=gd(r,"wire_c_scale",c.rc.wire_c_scale);} if(j.contains("debug")){auto&d=j["debug"]; c.debug.dump_candidate_cost=gb(d,"dump_candidate_cost",c.debug.dump_candidate_cost); c.debug.dump_per_net_detail=gb(d,"dump_per_net_detail",c.debug.dump_per_net_detail); c.debug.dump_plot_data=gb(d,"dump_plot_data",c.debug.dump_plot_data);} return true; }
bool ExperimentConfig::validate(std::string& e) const { if(input.common_lef.empty()||input.hbt_lef.empty()||input.upper_lef.empty()||input.bottom_lef.empty()||input.def_file.empty()){e="input path missing: common/hbt/upper/bottom/def must be non-empty"; return false;} return true; }
PDTreeRouter::Params ExperimentConfig::buildRouterParams() const { PDTreeRouter::Params p; p.source_res=rc.source_res; p.default_sink_cap=rc.default_sink_cap; p.hbt_res=rc.hbt_res*rc.hbt_rc_scale; p.hbt_cap=rc.hbt_cap*rc.hbt_rc_scale; p.max_candidate_parents=pd_tree.max_candidate_parents; p.max_candidate_hbts=pd_tree.max_candidate_hbts; p.beam_width_3d=pd_tree.beam_width_3d; p.beam_branch_candidates_3d=pd_tree.beam_branch_candidates_3d; p.max_local_hbt_candidates=pd_tree.max_local_hbt_candidates; p.max_hbt_nearest_k=pd_tree.max_hbt_nearest_k; p.verbose=pd_tree.verbose; if(cost_mode=="baseline"){ p.weight_avg_delay=0.0; p.weight_max_delay=0.0; p.weight_hbt_depth=0.0; p.weight_hbt_stack=0.0; p.weight_hbt_fanout=0.0; p.weight_hbt_scarcity=0.0; p.weight_hbt_position=0.0; p.weight_wirelength=std::max(1e-5,cost_weights.wirelength); p.weight_stretch=std::max(1e-5,cost_weights.stretch);} else { p.weight_avg_delay=cost_weights.avg_delay; p.weight_max_delay=cost_weights.max_delay; p.weight_wirelength=cost_weights.wirelength; p.weight_hbt_count=cost_weights.hbt_count; p.weight_stretch=cost_weights.stretch; p.weight_hbt_depth=cost_weights.hbt_depth; p.weight_hbt_stack=cost_weights.hbt_stack; p.weight_hbt_fanout=cost_weights.hbt_fanout; p.weight_hbt_scarcity=cost_weights.hbt_scarcity; p.weight_hbt_position=cost_weights.hbt_position; p.weight_hbt_subtree_wire=cost_weights.hbt_subtree_wire; p.weight_hbt_subtree_delay_proxy=cost_weights.hbt_subtree_delay_proxy;} return p; }
std::string ExperimentConfig::dumpJsonString() const { json j; j["experiment_name"]=experiment_name; j["benchmark"]=benchmark; j["cost_mode"]=cost_mode; return j.dump(2); }
